config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  devise_for :users

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  mount_uploader :backup, BackupUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	before_save { self.email = email.downcase}
#	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX},
						uniqueness: { case_sensitives: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	p pictures_path
    '/pictures'
  end

  def after_sign_out_path_for(resource)
  	root_path
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  def drop
  end

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
    @picture = Picture.new
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json 

  def create
    #Saving to Amazon S3
    @picture = Picture.new(picture: params[:file], backup: params[:file])
    
    #NOT saving to Amazon S3
    # @picture = Picture.new(picture: params[:file])

    if @picture.save!
      p "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
      p @picture
      p @picture.picture.file
      respond_to do |format|
        format.json{ render :json => @picture }
      end
    end
  end




 #  def create
 # #   @picture = Picture.new(picture_params)
 #  #  binding.pry
 #    respond_to do |format|
 #      if true
 #        p "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
 #        # @picture.picture = picutre_params[:picture]
 #        # @picture.save
        
 #        params[:picture]['picture'].each {|param|
 #          p "================="
 #          p param

 #          @picture = Picture.new(picture_params)
 #          p @picture.class
 #          p @picture.picture.class
 #          @picture.picture = param
 #          @picture.save
 #          p "================="
 #        }
        
 #        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
 #        format.json { render :show, status: :created, location: @picture }
 #      else
 #        format.html { render :new }
 #        format.json { render json: @picture.errors, status: :unprocessable_entity }
 #      end
 #    end
 #  end

 # def create
 #  p "--------------"
 #  p params[:file]
 #  p "--------------"
 #    @picture = Picture.new(picture: params[:file])
 #    if @picture.save
 #      respond_to do |format|
 #        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
 #        format.json { render :show, status: :ok, location: @picture }
 #      end
 #    else
 #      respond_to do |format|
 #        format.html { render :new }
 #        format.json { render json: @picture.errors, status: :unprocessable_entity }
 #      end
 #    end
 #  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:picture)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def concact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = "AnDI Web App"
		if (page_title.empty?)
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/manipulator.rb
module Manipulator
  def polaroidImage(a_img, outputFile = './Polaroid.jpg')
      divX = 3
      divY = 3
      minAngle = -5
      maxAngle = 5
      p "========================="
      p a_img
      # img = Magick::Image.read(file).shift
      img = a_img
      compImage = Magick::ImageList.new
      bImage = Magick::Image.new(img.columns + divX * 23 + 10, img.rows + divY * 23 + 10) {
        self.background_color = "white"
      }
      compImage[0] = bImage

      partWidth = (img.columns / divX).truncate
      partHeight = (img.rows / divY).truncate
      draw = Magick::Draw.new

    # print "img.columns:" << img.columns.to_s << "\n"
    # print "img.rows: " << img.rows.to_s << "\n"
    for l_y in 0..(divY-1)
      for l_x in 0..(divX-1)
        cropSizeW = (l_x == divX-1) ? img.columns - ((divX -1) * partWidth) : partWidth
        cropSizeH = (l_y == divY-1) ? img.rows - ((divY -1) * partHeight) : partHeight
        # p l_x * partWidth, l_y * partHeight, cropSizeW, cropSizeH
        cropImage = img.crop(l_x * partWidth, l_y * partHeight, cropSizeW, cropSizeH) {
          self.background_color = "black"
        }
        cropImage = cropImage.polaroid(rand(10) - 5) {
          self.border_color = "#f8f8ff"
          self.undercolor = "none"
          self.shadow_color = "#202020"
        }
        bImage = bImage.composite(cropImage, (partWidth + 23) * l_x, (partHeight + 23) * l_y, Magick::OverCompositeOp)      
      end
    end
    bImage.format = "JPEG"
    bImage
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">AnDI Web App</a>
    by DI
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.jp/">News</a></li>
    </ul>
  </nav>
  <br>
  <% if user_signed_in? %>
    Logged in as <%= current_user.email %>. <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
  <% end %>
  
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
    <%= link_to "AnDI", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
         <li><%= link_to "Home",    root_path %></li>
         <li><%= link_to "Help",    help_path %></li>
          <li><% if user_signed_in? %> <%= link_to "logged in as " + current_user.email, '/pictures' %><% end %></li>
          <li>
            <% if user_signed_in? %>
            <%= link_to "Log out", destroy_user_session_path, :method => :delete %>
            <% else %>
            <%= link_to "Log in", new_user_session_path %>
            <% end %>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for @picture, method: :post, url: {:action => 'create'}, html: {id: 'picture-dropzone', class: 'dropzone form'} do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="fallback">
    <%= f.file_field :picture, multiple: true%>
    <%= f.submit "submit" %>
    
  </div>
  <!--<div class="actions">
  </div>-->
<% end %>

app/views/pictures/drop.html.erb
<%= form_tag '/media_contents', method: :post, class: "dropzone", id: "media-dropzone" do %>
  <div class="fallback">
    <%= file_field_tag "media", multiple: true%>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<script type="text/javascript" src="http://webos-goodies.googlecode.com/svn/trunk/products/jslib/draggable_grid/draggable_grid.js"></script>

<p id="notice"><%= notice %></p>

<br>
<p>
<h1>Pictures</h1>

<h2>Please push F5 once for avoiding bug that cannot show and upload pictures.</h2>

<%= render 'form' %>


</p>
<style type="text/css">
  .draggable {
    display: inline-block;
    vertical-align: top;
    width: 202px;
    height: 202px;
    zoom: 1;
    *display: inline;
  }
  </style>

<div id="grid" >
  <% @pictures.each do |picture| %>
  <div class="draggable">
    <%= picture.created_at.to_s.split(' ').first  %>
    <div id="no-turbolinks" data-no-turbolink><%= link_to image_tag(picture.picture.url(:thumb)), picture.picture.url(:browse) ,:rel => "lightbox[0]"%></div>
  </div>
  <% end %>
</div>

<script type="text/javascript">
  new DraggableGrid('grid',  { handleClass: 'handle' });
</script>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @picture.name %>
  <br>
  <%= image_tag @picture.picture %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.jp/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.jp/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">

	<div id="overlay" style="position:relative; marginLeft: 0px">

		<p class="resizeimage">
			<%= image_tag("home.jpg", alt: "Rails") %>
		</p>
		<div id="welcome_msg" style="position:absolute; right: 60px; top: 190px">

			<h1>Welcome to AnDI</h1>
			<h2>
				This is the home page for the
				<a href="http://railstutorial.jp/">Ruby on Rails Tutorial</a>
				sample application.
			</h2>

			<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
		</div>
	</div>

</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>
<div id='user_nav'>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or
    <%= link_to "Sign in", new_user_session_path %>
  <% end %>
</div>